---
- name: install uwsgi inside virtualenv
  pip: virtualenv=/opt/uwsgi name=uwsgi
  notify: restart uwsgi

- name: create uwsgi.d
  file: path=/opt/uwsgi/etc/uwsgi.d state=directory

- name: create uwsgi fastrouter config
  template: src=uwsgi_fastrouter.j2 dest=/opt/uwsgi/etc/uwsgi.d/fastrouter.ini

- name: chown uwsgi fastrouter config to nobody
  file: path=/opt/uwsgi/etc/uwsgi.d/fastrouter.ini owner=nobody group=nogroup

- name: create uwsgi init script
  template: src=uwsgi_init.j2 dest=/etc/init.d/uwsgi
  notify: restart uwsgi
